# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 172272abcf1cb4be3a63e99dece750d41f18afea6aee6a53db74c127ecdc0b4452e2d1eca73c8e2a1b0bb9507dd00ade086c941712b0863601e45b48200257b4

test:
  secret_key_base: 7ec29ba054b37bd7a2c9e2b639a68dd6768a6f13fecdef2b69dbdc1d7a4c96322ec470d80064190c48927faca4d5cfb1771b5142efb76c29605b1854cd1257e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
